#ifndef CONNECTION_MANAGER_H
#define CONNECTION_MANAGER_H

#include "PlatformCTypes.h"

typedef enum
{
    CM_SERVER_STATUS_IDLE = 0,
    CM_SERVER_STATUS_LS_CONNECTING,
    CM_SERVER_STATUS_LS_CONNECTED,
    CM_SERVER_STATUS_CS_CONNECTING,
    CM_SERVER_STATUS_CS_CONNECTED,
    CM_SERVER_STATUS_ONLINE,
}CMServerStatus_t;

#endif // !CONNECTION_MANAGER_H
