#ifndef PLATFORM_OPTION_H
#define PLATFORM_OPTION_H

#include "PlatformUserOption.h"

#define PLATFORM_PROTOCOL_VERSION "000.000.000.001"
#define PLATFORM_DEVID_LEN  64
#define PLATFORM_MODEL_LEN 64
#define PLATFORM_PIN_LEN  32
#define PLATFORM_VERSION_LEN 15
#define PLATFORM_SESSIONKEY_LEN 16
#define PLATFORM_TOKEN_LEN 32
#define PLATFORM_CTEI_LEN 15

#define PLATFORM_FACTORY_NAME_LEN 32

#ifndef PLATFORM_CLIENT_CONNECT_NUM
#define PLATFORM_CLIENT_CONNECT_NUM 5 //客户端连接的数量
#endif

#ifndef PLATFORM_SERVER_URL
#define PLATFORM_SERVER_URL "180.100.133.131"
#define PLATFORM_SERVER_PORT 9017
#endif

//#ifndef PLATFORM_DEVICE_VERSION
//#define PLATFORM_DEVICE_VERSION "000.000.000.001"
//#endif

#endif // !PLATFORM_OPTION_H
